### ISSUE TITLE
[Feat] 상품, 카테고리 조회

### ISSUE THREAD

**Issue by yoonnable** [f-lab-edu/e-commerce-mall#14]
## 📝 개요
- 상품, 카테고리를 조회 기능을 구현합니다.

## ✅ TO-DO
- [ ] 최상위 카테고리 리스트와 그 중 선택된 카테고리의 하위 카테고리 리스트 조회 기능 구현
- [ ] 각 카테고리별 상품 리스트 조회 구현
- [ ] 상품 정렬 순서, 필터 적용한 조회 구현

## 📌 ETC
-
