### ISSUE TITLE
[Test] 테스트 코드 작성

### ISSUE THREAD

**Issue by yoonnable** [f-lab-edu/e-commerce-mall#22]
## 📝 개요
- 현재까지 구현한 기능의 테스트 코드를 작성하고 검토합니다.

## ✅ TO-DO
- [x] 로그인 성공/실패 테스트 코드 작성
- [x] 로그아웃 성공/실패 테스트 코드 작성
- [x] 토큰 재발급 성공/실패 테스트 코드 작성
- [x] 상품, 카테고리 조회 성공/실패 테스트 코드 작성
- [x] 상품 검색 성공/실패 테스트 코드 작성
- [x] 상품 등록/업데이트 실패 테스트 코드 작성
- [x] 코드 커버리지 확인

## 📌 ETC
-
