### ISSUE TITLE
[Feat] 상품 주문

### ISSUE THREAD

**Issue by yoonnable** [f-lab-edu/e-commerce-mall#26]
## 📝 개요
- 상품 주문 기능을 구현합니다.
- 상품 상세 페이지에서의 즉시 구매와 장바구니에서 선택한 상품 구매가 가능합니다.
- 두 경우 모두 결제 전 주문 정보를 입력합니다.
- 결제가 완료되었다는 가정 하에, 입력한 정보로 주문을 완료합니다.

## ✅ TO-DO
- [ ] 주문 정보 입력 전처리 API를 구현합니다.
- [ ] 주문 기능을 구현합니다.
- [ ] 테스트 코드 작성 및 커버리지 측정을 완료합니다.

## 📌 ETC
- 결제 기능은 추후 개발 예정입니다.
