### ISSUE TITLE
[Feat] Spring REST Docs 도입

### ISSUE THREAD

**Issue by yoonnable** [f-lab-edu/e-commerce-mall#28]
## 📝 개요
- API 문서화를 위한 Spring REST Docs 도입합니다.

## ✅ TO-DO
- [x] Gradle에 Spring REST Docs 설정 추가
- [x] 테스트 코트에 적용 (snippet 생성)
- [x] adoc 문서 편집 (html 생성)

## 📌 ETC
-
